name: Test Feed-Monitor
on: [push]
jobs:
  Run-Tests:
    runs-on: ubuntu-latest
    container: golang:1.17-buster
    services:
      gotify:
        image: gotify/server:2.1.4
        ports:
          - "80:80"
    steps:
      - uses: actions/checkout@v3
      - name: Setup Gotify Server
        run: |
          # install jq
          apt-get update
          apt-get install -y jq
          # Create new gotify application and retrieve token
          GOTIFY_URL=http://localhost
          echo "GOTIFY_URL: $GOTIFY_URL"
          GOTIFY_TOKEN=$(curl -X POST -u admin:admin "$GOTIFY_URL/application" -d '{"name":"GitHub Actions", "description":"GitHub Actions"}' | jq -r '.token')
          echo "GOTIFY_TOKEN: $GOTIFY_TOKEN"
          export GOTIFY_TOKEN
          export GOTIFY_URL
      - name: Build Gotify Plugin
        run: bash ./bin/build_gotify.sh
      - name: Run Tests
        run: bash ./bin/run_tests.sh
      - uses: codecov/codecov-action@v2
